export const ADD_POINT_INPUT = 'ADD_POINT_INPUT';
export const SET_POINT_PLACE = 'SET_POINT_PLACE';
export const SET_POINT_ARRIVAL_TIME = 'SET_POINT_ARRIVAL_TIME';
export const SET_POINT_DEPARTURE_TIME = 'SET_POINT_DEPARTURE_TIME';
export const SET_POINT_DURATION = 'SET_POINT_DURATION';

// suggest point name
export const REQUEST_POINT = 'REQUEST_POINT';
export const RECEIVE_POINT = 'RECEIVE_POINT';
export const CLEAR_SUGGESTED_TEXT = 'CLEAR_SUGGESTED_TEXT';

// search
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';

// direction
export const REQUEST_DIRECTION = 'REQUEST_DIRECTION';
export const RECEIVE_DIRECTION = 'RECEIVE_DIRECTION';
