// @flow
export const ADD_POINT_INPUT = 'ADD_POINT_INPUT';
export const SET_POINT_PLACE = 'SET_POINT_PLACE';
export const SET_POINT_ARRIVED_AT = 'SET_POINT_ARRIVED_AT';
export const SET_POINT_DURATION = 'SET_POINT_DURATION';

// suggest point name
export const REQUEST_POINT_NAME_SUGGEST = 'REQUEST_POINT_NAME_SUGGEST';
export const RECEIVE_POINT_NAME_SUGGEST = 'RECEIVE_POINT_NAME_SUGGEST';
export const CLEAR_SUGGESTED_TEXT = 'CLEAR_SUGGESTED_TEXT';

