// @flow
export const ADD_POINT_INPUT = 'ADD_POINT_INPUT';
export const SET_POINT_PLACE = 'SET_POINT_PLACE';
export const SET_POINT_ARRIVED_AT = 'SET_POINT_ARRIVED_AT';
export const SET_POINT_DURATION = 'SET_POINT_DURATION';
